### ISSUE TITLE
terraform 0.12.12 + terragrunt 0.20.4 (HCL)

### ISSUE THREAD

**Issue by zelig81** [4ops/vscode-language-terraform#1]
I've got wrong syntax highlighting while creating terragrunt.hcl file:

- lines 1-10, do not understand why it is wrong
- line 13, vscode does not do wrap lines (it is enabled generally for all files)
- lines 20-27, do not understand why it is wrong + last curly braces of 'terraform' wrongly highlighted as invalid code

In archive you can see the file itself + screenshot of the problem

[Archive.zip](https://github.com/4ops/vscode-language-terraform/files/3775628/Archive.zip)

**Comment by 4ops** [comment]
Only pure Terraform syntax supported, but not terragrunt :(
Try to work with that extension: https://marketplace.visualstudio.com/items?itemName=mauve.terraform

**Comment by zelig81** [comment]
Thank you :)

**Comment by 4ops** [comment]
@zelig81 can you try new release 0.2.0 with Terragrunt supported? Thanks

**Comment by zelig81** [comment]
@4ops thank you - looks awesome (much better than mauve.terraform!!!!)
