### ISSUE TITLE
Incorrect syntax highlighting for labeled include blocks in terragrunt configuration

### ISSUE THREAD

**Issue by erclu** [4ops/vscode-language-terraform#11]
A recent terragrunt release changed how include blocks behave:

https://github.com/gruntwork-io/terragrunt/releases/tag/v0.32.0

they now recommend adding a label to all existing include blocks. This is how the most recent version of this extension highlights the specified syntax:

![image](https://user-images.githubusercontent.com/30255227/135647832-b4c00a8d-4e4e-4361-b601-1250e43868b6.png)

**Comment by hariscodes** [comment]
I think this was fixed by #15, and can be closed.
