### ISSUE TITLE
Syntax highlighting support for multiple includes in terragrunt.hcl

### ISSUE THREAD

**Issue by cruftyoldsysadmin** [4ops/vscode-language-terraform#14]
[Terragrunt 0.32](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.32.0) released support for multiple include files.  Previously the only supported syntax was a global include:

```hcl
include {
  path = find_in_parent_folders()
 }
 ```
 
 Now you can have multiple named includes (which allowed me to cut down my Terragrunt repo by about 55%). Currently the new syntax does not get highlighted correctly, and in my theme (`dark (Visual Studio)`), the multiple configuration blocks are all red.  

### Multiple  include syntax
 ```hcl
include {
   path = find_in_parent_folders()
}
 
include "vpc" {
  path = find_in_parent_folders("_envcommon/vpc-deps.hcl")
}

include "fargate" {
  path = find_in_parent_folders("_envcommon/ecs-deps.hcl")
}
```
 
### Resources
* [Even More DRY and Maintainable Code With Terragrunt](https://blog.gruntwork.io/even-more-dry-and-maintainable-code-with-terragrunt-5738d1ffc1c9)
* [Terragrunt v0.32](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.32.0)

**Comment by cruftyoldsysadmin** [comment]
I've added a PR to this, #15

**Comment by 4ops** [comment]
Merged

**Comment by cruftyoldsysadmin** [comment]
Thanks!
