### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by fahmirasdi** [4ops/vscode-language-terraform#2]
Hi,

Can you integrate basic auto-complete on resources mostly aws on this extension?

**Comment by Charliekenney23** [comment]
@4ops I would very much like to implement this if you haven't started. Do you have any thoughts on how this should be done?

I know with [mauve/vscode-terraform](https://github.com/mauve/vscode-terraform) they're using [this tool](https://github.com/ranga543/terraform-docs-scrape) (which is kinda broken) to scrape the terraform doc sites for a given provider and map it over to JSON of shape.
```
{
  resources: Resource[];
  dataSources: DataSource[];
}
```

We could do this here, correctly, and automate PRs to update on minor releases of providers via Github actions.

**Comment by 4ops** [comment]
@Charliekenney23 I'm sorry - my new work takes a lot of time for me. Maybe in next release..

> I would very much like to implement this if you haven't started

Sure, you are welcome.

**Comment by 4ops** [comment]
> Hi,
> 
> Can you integrate basic auto-complete on resources mostly aws on this extension?

Planned to add AWS snippets
